<?php

namespace BPashkevich\ProductBundle\Repository;

/**
 * ConfigurableProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurableProductRepository extends \Doctrine\ORM\EntityRepository
{
}
