app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix:   /

b_pashkevich_product:
    resource: "@BPashkevichProductBundle/Resources/config/routing.yml"
    prefix:   /

b_pashkevich_user:
    resource: "@BPashkevichUserBundle/Resources/config/routing.yml"
    prefix:   /


