b_pashkevich_user_user:
    resource: "@BPashkevichUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

b_pashkevich_user_homepage:
    path:     /
    defaults: { _controller: BPashkevichUserBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: b_pashkevich_user.login_controller:loginAction }

logout:
    path:     /logout
    defaults: { _controller: b_pashkevich_user.login_controller:logoutAction }
