services:
    b_pashkevich_user.user_srvice:
        class: BPashkevich\UserBundle\Services\UserService
        arguments: ['@doctrine.orm.entity_manager']


    b_pashkevich_user.login_controller:
        class: BPashkevich\UserBundle\Controller\LoginController
        arguments: ['@security.authentication_utils']