index:
    path:     /
    defaults: { _controller: app.default_controller:indexAction }

getALLProducts:
    path:     /api/getALLProducts
    defaults: { _controller: app.product_api_controller:getALLProductsAction }

getProductById:
    path:     /api/getProductById
    defaults: { _controller: app.product_api_controller:getProductByIdAction }

getProductCategory:
    path:     /api/getProductCategory
    defaults: { _controller: app.product_api_controller:getProductCategoryAction }

getProductData:
    path:     /api/getProductData
    defaults: { _controller: app.product_api_controller:getProductDataAction }

getSingleProductMainInfo:
    path:     /api/getSingleProductMainInfo
    defaults: { _controller: app.product_api_controller:getSingleProductMainInfoAction }

getAttributes:
    path:     /api/getAttributes
    defaults: { _controller: app.product_api_controller:getAttributesAction}

getALLCategories:
    path:     /api/getALLCtegories
    defaults: { _controller: app.category_api_controller:getALLCategoriesAction }

getCategoryById:
    path:     /api/getCategoryById
    defaults: { _controller: app.category_api_controller:getCategoryByIdAction }

getProductsFromCategory:
    path:     /api/getProductsFromCategoryMainInfo
    defaults: { _controller: app.category_api_controller:getProductsFromCategoryMainInfoAction }

getConfigProductFromCategoryMainInfo:
    path:     /api/getConfigProductFromCategoryMainInfo
    defaults: { _controller: app.category_api_controller:getConfigProductFromCategoryMainInfoAction }

getSimpleProductsFromCategoryMainInfoAction:
    path:     /api/getSimpleProductsFromCategoryMainInfoAction
    defaults: { _controller: app.category_api_controller:getSimpleProductsFromCategoryMainInfoAction }

getALLConfigurableProducts:
    path:     /api/getALLConfigurableProducts
    defaults: { _controller: app.configurable_product_api_controller:getALLConfigurableProductsAction }

getALLAttributes:
    path:     /api/getALLAttributes
    defaults: { _controller: app.attribute_api_controller:getALLAttributesAction }

getALLProductsFromCart:
    path:     /api/getALLProductsFrom
    defaults: { _controller: app.cart_api_controller:getALLProductsFromCartAction }

getCategoryShortInfo:
    path:     /api/getCategoryShortInfo
    defaults: { _controller: app.category_api_controller:getCategoryShortInfoAction }

getConfigProductMainInfo:
    path:     /api/getConfigProductMainInfo
    defaults: { _controller: app.configurable_product_api_controller:getConfigProductMainInfoAction }

getConfigurableProductForShow:
    path:     /api/getConfigurableProductForShow
    defaults: { _controller: app.configurable_product_api_controller:getConfigurableProductForShowAction }

getProductsByParam:
    path:     /api/getProductsByParam
    defaults: { _controller: app.product_api_controller:getProductsByParamAction }

getUsersMainInfo:
    path:     /api/getALLUsers
    defaults: { _controller: app.user_api_controller:getALLUsersAction }

getUserById:
    path:     /api/getUserById
    defaults: { _controller: app.user_api_controller:getUserByIdAction }

getAttributeById:
    path:     /api/getAttributeById
    defaults: { _controller: app.attribute_api_controller:getAttributeByIdAction }

getMandatorAttributes:
    path:     /api/getMandatorAttributes
    defaults: { _controller: app.attribute_api_controller:getMandatoryAttributesAction }

getNotMandatorAttributes:
    path:     /api/getNotMandatorAttributes
    defaults: { _controller: app.attribute_api_controller:getNotMandatoryAttributesAction }

getALLAttributeValues:
    path:     /api/getALLAttributeValues
    defaults: { _controller: app.attribute_value_api_controller:getALLAttributeValuesAction }

getAttributeValueById:
    path:     /api/getAttributeValueById
    defaults: { _controller: app.attribute_value_api_controller:getAttributeValueByIdAction }

setAttributeById:
    path:     /api/setAttributeById
    defaults: { _controller: app.attribute_api_controller:saveAttributeAction }

setAttributeValueById:
    path:     /api/setAttributeValueById
    defaults: { _controller: app.attribute_value_api_controller:saveAttributeValueAction }

setCategoryById:
    path:     /api/setCategoryById
    defaults: { _controller: app.category_api_controller:saveCategoryAction }

setConfigurableProductById:
    path:     /api/setConfigurableProductById
    defaults: { _controller: app.configurable_producte_api_controller:saveConfigurableProductAction }

setProductById:
    path:     /api/setProductById
    defaults: { _controller: app.product_api_controller:saveProductAction }

setUserById:
    path:     /api/setUserById
    defaults: { _controller: app.user_api_controller:saveUserAction }


deleteAttributeById:
    path:     /api/deleteAttributeById
    defaults: { _controller: app.attribute_api_controller:deleteAttributeAction }

deleteAttributeValueById:
    path:     /api/deleteAttributeValueById
    defaults: { _controller: app.attribute_value_api_controller:deleteAttributeValueAction }

deleteCategoryById:
    path:     /api/deleteCategoryById
    defaults: { _controller: app.category_api_controller:deleteCategoryAction }

deleteConfigurableProductById:
    path:     /api/deleteConfigurableProductById
    defaults: { _controller: app.configurable_producte_api_controller:deleteConfigurableProductAction }

deleteProductById:
    path:     /api/deleteProductById
    defaults: { _controller: app.product_api_controller:deleteProductAction }

deleteUserById:
    path:     /api/deleteUserById
    defaults: { _controller: app.user_api_controller:deleteUserAction }

deleteALLAttributesById:
    path:     /api/deleteALLAttributesById
    defaults: { _controller: app.attribute_api_controller:deleteALLAttributesAction }

deleteALLAttributeValuesById:
    path:     /api/deleteALLAttributeValuesById
    defaults: { _controller: app.attribute_value_api_controller:deleteALLAttributeValuesAction }

deleteALLCategoriesById:
    path:     /api/deleteALLCategoriesById
    defaults: { _controller: app.category_api_controller:deleteALLCategoriesAction }

deleteALLConfigurableProductsById:
    path:     /api/sdeleteALLConfigurableProductsById
    defaults: { _controller: app.configurable_producte_api_controller:deleteALLConfigurableProductsAction }

deleteALLProductsById:
    path:     /api/deleteALLProductsById
    defaults: { _controller: app.product_api_controller:deleteALLProductsAction }

deleteALLUsersById:
    path:     /api/deleteALLUsersById
    defaults: { _controller: app.user_api_controller:deleteALLUsersAction }
