attribute_index:
    path:     /
    defaults: { _controller: "BPashkevichProductBundle:Attribute:index" }
    methods:  GET

attribute_show:
    path:     /{id}/show
    defaults: { _controller: "BPashkevichProductBundle:Attribute:show" }
    methods:  GET

attribute_new:
    path:     /new
    defaults: { _controller: "BPashkevichProductBundle:Attribute:new" }
    methods:  [GET, POST]

attribute_edit:
    path:     /{id}/edit
    defaults: { _controller: "BPashkevichProductBundle:Attribute:edit" }
    methods:  [GET, POST]

attribute_delete:
    path:     /{id}/delete
    defaults: { _controller: "BPashkevichProductBundle:Attribute:delete" }
    methods:  DELETE
