configurableproduct_index:
    path:     /
    defaults: { _controller: b_pashkevich_product.configurable_product_controller:indexAction }
    methods:  GET

configurableproduct_show:
    path:     /{id}/show
    defaults: { _controller: b_pashkevich_product.configurable_product_controller:showAction }
    methods:  GET

configurableproduct_new:
    path:     /new
    defaults: { _controller: b_pashkevich_product.configurable_product_controller:newAction }
    methods:  [GET, POST]

configurableproduct_save:
    path:     /save
    defaults: { _controller: b_pashkevich_product.configurable_product_controller:saveAction }
    methods:  [POST]

configurableproduct_edit:
    path:     /{id}/edit
    defaults: { _controller: b_pashkevich_product.configurable_product_controller:editAction }
    methods:  [GET, POST]

configurableproduct_update:
    path:     /{id}/update
    defaults: { _controller: b_pashkevich_product.configurable_product_controller:updateAction }
    methods:  [GET, POST]

configurableproduct_delete:
    path:     /{id}/delete
    defaults: { _controller: b_pashkevich_product.configurable_product_controller:deleteAction }
    methods:  DELETE
