product_index:
    path:     /
    defaults: { _controller: b_pashkevich_product.product_controller:indexAction }
    methods:  GET

product_show:
    path:     /{id}/show
    defaults: { _controller: b_pashkevich_product.product_controller:showAction }
    methods:  GET

product_new:
    path:     /new
    defaults: { _controller: b_pashkevich_product.product_controller:newAction }
    methods:  [GET, POST]

product_new_child:
    path:     /new/{id}
    defaults: { _controller: b_pashkevich_product.product_controller:newAction }
    methods:  [GET, POST]

product_save:
    path:     /save
    defaults: { _controller: b_pashkevich_product.product_controller:saveAction }
    methods:  [POST]

product_save_child:
    path:     /save/{id}
    defaults: { _controller: b_pashkevich_product.product_controller:saveAction }
    methods:  [POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: b_pashkevich_product.product_controller:editAction }
    methods:  [GET, POST]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: b_pashkevich_product.product_controller:deleteAction }
    methods:  DELETE
