b_pashkevich_product_product:
    resource: "@BPashkevichProductBundle/Resources/config/routing/product.yml"
    prefix:   /product

b_pashkevich_product_category:
    resource: "@BPashkevichProductBundle/Resources/config/routing/category.yml"
    prefix:   /category

b_pashkevich_product_image:
        resource: "@BPashkevichProductBundle/Resources/config/routing/image.yml"
        prefix:   /image

b_pashkevich_product_productorder:
        resource: "@BPashkevichProductBundle/Resources/config/routing/productorder.yml"
        prefix:   /productorder

b_pashkevich_product_homepage:
    path:     /
    defaults: { _controller: b_pashkevich_product.product_controller:indexAction }

b_pashkevich_product_attribute:
    resource: "@BPashkevichProductBundle/Resources/config/routing/attribute.yml"
    prefix:   /attribute

b_pashkevich_product_configurableproduct:
        resource: "@BPashkevichProductBundle/Resources/config/routing/configurableproduct.yml"
        prefix:   /configurableproduct

b_pashkevich_product_attributevalue:
        resource: "@BPashkevichProductBundle/Resources/config/routing/attributevalue.yml"
        prefix:   /attributevalue
