services:
    b_pashkevich_product.attribure_srvice:
        class: BPashkevich\ProductBundle\Services\AttributeService
        arguments: ['@doctrine.orm.entity_manager']

    b_pashkevich_product.attribure_value_srvice:
        class: BPashkevich\ProductBundle\Services\AttributeValueService
        arguments: ['@doctrine.orm.entity_manager']

    b_pashkevich_product.image_srvice:
        class: BPashkevich\ProductBundle\Services\ImageService
        arguments: ['@doctrine.orm.entity_manager']

    b_pashkevich_product.product_srvice:
        class: BPashkevich\ProductBundle\Services\ProductService
        arguments: ['@doctrine.orm.entity_manager', '@session', '@b_pashkevich_product.db_service']

    b_pashkevich_product.configurable_product_srvice:
        class: BPashkevich\ProductBundle\Services\ConfigurableProductService
        arguments: ['@doctrine.orm.entity_manager', '@b_pashkevich_product.db_service',
         '@b_pashkevich_product.product_srvice']

    b_pashkevich_product.category_srvice:
        class: BPashkevich\ProductBundle\Services\CategoryService
        arguments: ['@doctrine.orm.entity_manager']

#    b_pashkevich_product.productOrder_srvice:
#        class: BPashkevich\ProductBundle\Services\ProductOrderService
#        arguments: ['@doctrine.orm.entity_manager']

    b_pashkevich_product.configurable_product_controller:
        class: BPashkevich\ProductBundle\Controller\ConfigurableProductController
        arguments: ['@b_pashkevich_product.configurable_product_srvice', '@b_pashkevich_product.category_srvice',
         '@b_pashkevich_product.image_srvice', '@b_pashkevich_product.attribure_srvice',
          '@b_pashkevich_product.attribure_value_srvice',]

    b_pashkevich_product.product_controller:
        class: BPashkevich\ProductBundle\Controller\ProductController
        arguments: ['@b_pashkevich_product.product_srvice', '@b_pashkevich_product.category_srvice',
         '@b_pashkevich_product.image_srvice', '@b_pashkevich_product.attribure_srvice',
          '@b_pashkevich_product.attribure_value_srvice', '@b_pashkevich_product.configurable_product_srvice']

    b_pashkevich_product.category_controller:
        class: BPashkevich\ProductBundle\Controller\CategoryController
        arguments: ['@b_pashkevich_product.category_srvice', '@b_pashkevich_product.product_srvice', '@b_pashkevich_product.configurable_product_srvice']

    b_pashkevich_product.attribute_controller:
        class: BPashkevich\ProductBundle\Controller\AttributeController
        arguments: ['@b_pashkevich_product.attribure_srvice']

    b_pashkevich_product.attribute_value_controller:
        class: BPashkevich\ProductBundle\Controller\AttributeValueController
        arguments: ['@b_pashkevich_product.attribure_value_srvice', '@b_pashkevich_product.category_srvice',
         '@b_pashkevich_product.attribure_srvice']

    b_pashkevich_product.cart_controller:
        class: BPashkevich\ProductBundle\Controller\CartController
        arguments: ['@b_pashkevich_product.category_srvice', '@b_pashkevich_product.product_srvice']

    b_pashkevich_product.db_service:
        class: BPashkevich\ProductBundle\Services\DBService
        arguments: []

#    # Fixtures services
#    b_pashkevich_product.fixture:
#        class: BPashkevich\ProductBundle\DataFixtures\ORM\LoadCommonData
#        tags: [doctrine.fixture.orm]
